export const countryData = {
  CountryList: [
    { Code: "IN", Name: "India" },
    { Code: "AF", Name: "Afghanistan" },
    { Code: "AL", Name: "Albania" },
    { Code: "DZ", Name: "Algeria" },
    { Code: "AU", Name: "Australia" },
    { Code: "BD", Name: "Bangladesh" },
    { Code: "BT", Name: "Bhutan" },
    { Code: "CA", Name: "Canada" },
    { Code: "CN", Name: "China" },
    { Code: "FR", Name: "France" },
    { Code: "DE", Name: "Germany" },
    { Code: "ID", Name: "Indonesia" },
    { Code: "JP", Name: "Japan" },
    { Code: "MY", Name: "Malaysia" },
    { Code: "MV", Name: "Maldives" },
    { Code: "NP", Name: "Nepal" },
    { Code: "SG", Name: "Singapore" },
    { Code: "LK", Name: "Sri Lanka" },
    { Code: "TH", Name: "Thailand" },
    { Code: "AE", Name: "United Arab Emirates" },
    { Code: "GB", Name: "United Kingdom" },
    { Code: "US", Name: "United States" },
  ],
};
